### ISSUE TITLE
Wireless debugging doesn't work with CLI

### ISSUE THREAD

**Issue by HeroGalak** [revanced/revanced-cli#110]
### Type

Error while running the CLI

### Bug description

If CLI is used with wireless debugging, passing ip address and port of the device to -d raise an error during build process.
Error: `java.lang.IllegalArgumentException: No such device with name ipaddr:port`

### Steps to reproduce

Activate wireless debugging on device;

Connect device to pc using: adb pair `ipaddr:port`
then use the pin code to verify the connection;

Once connection is established run: `java -jar revanced-cli-2.8.3-all.jar -a youtube.apk -c -d ipaddr:port -o revanced.apk -b revanced-patches-2.31.0.jar -m integrations.apk -e custom-branding -e enable-debugging -i settings`

### Relevant log output

```shell
java.lang.IllegalArgumentException: No such device with name ipaddr:port
```

**Comment by oSumAtrIX** [comment]
You need a wired connection.

**Comment by j4k0xb** [comment]
Has always worked fine for me
Did you run `adb connect ip:port` before?

**Comment by oSumAtrIX** [comment]
He was using the wrong syntax, but this should indeed work.

**Comment by HeroGalak** [comment]
Problem solved using `adb connect ip:port` without using a pairing code
