### ISSUE TITLE
feat: Install already built APK by mounting multiple times without having to rebuild it each time

### ISSUE THREAD

**Issue by DerivativeOfLog7** [ReVanced/revanced-cli#123]
### Type

Functionality

### Issue

If someone has multiple rooted devices with ReVanced installed and wants to update all of them, which on root is done with --mount, the patched APK has to be built each time, which is not necessary after the first device

### Feature

Give an option to install an already existing APK my mounting

### Motivation

Makes updating/reinstalling the same patched APK quicker, especially for lower speed computers

**Comment by Shadow-Hunt3r** [comment]
when installing multiple copies then you could include an output instruction at the end of your file like so `-o /path/to/file.apk` which it creates an apk file named at your choice, a good example would be `revanced-cli -b revanced-patches.jar -a '/path/to/file/<filename>.apk' -o '/path/to/file/Revanced-<filename>.apk'`
whenever done so then you could inject the apk using `adb install -r /path/to/file/<filename>.apk` command

**Comment by bitingsock** [comment]
a normal install will `fail to collect certificates`
but the cli includes mounting as a part of the install utility
`java.exe -jar "cli.jar" utility install --apk "output.apk" --mount "com.google.android.youtube" yourdeviceserial`

**Comment by oSumAtrIX** [comment]
Open a new issue

**Comment by bitingsock** [comment]
I should have worded differently. I meany to reply to @Shadow-Hunt3r to say his method would likely not work and that OP should instead use the utilities built into the cli to do what he is asking. It should work this way.
