### ISSUE TITLE
bug: error when trying to build client

### ISSUE THREAD

**Issue by moosje2003** [revanced/revanced-cli#125]
### Type

Other

### Bug description

i get an error while trying to build the revanced client
### Relevant log output

```shell
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\maart\Downloads\revanced-cli\build.gradle.kts' line: 8

* What went wrong:
System.getenv("GITHUB_ACTOR") must not be null
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/61630365/188325706-43528637-46a6-41cf-a012-8f67312927ec.png)

**Comment by Aunali321** [comment]
Read the docs: https://github.com/revanced/revanced-documentation/wiki/Building-from-source.
