### ISSUE TITLE
feat: allow unsigned final files

### ISSUE THREAD

**Issue by j-hc** [revanced/revanced-cli#129]
### Type

Functionality

### Issue

there is no way to build an unsigned apk if it isnt going to be mounted

### Feature

allow unsigned final files

### Motivation

the user might want to mount the root build later so signing it should always be optional.

**Comment by oSumAtrIX** [comment]
You can mount signed files, so that does not oppose any issues.

**Comment by j-hc** [comment]
> You can mount signed files, so that does not oppose any issues.

that does not mean i dont want to skip signing them but whatever

**Comment by oSumAtrIX** [comment]
It's not intended to skip it if you don't use the `--mount` option.  Ommit `-c` and you have the unsigned file.
