### ISSUE TITLE
bug: <Failed to clean up cache directory> in version 2.10.0

### ISSUE THREAD

**Issue by webzeroacs** [revanced/revanced-cli#134]
### Type

Other

### Bug description

Failed to clean up cache directory in Version 2.10.0.
It works in version 2.9.10.

### Steps to reproduce

"C:\Program Files\Zulu\zulu-17\bin\java.exe" -jar revanced-cli.jar -a youtube.apk -o revanced.apk -b revanced-patches.jar -m app-release-unsigned.apk -c

### Relevant log output

```shell
nothing
```

### Screenshots or videos

![revanced-cli-2 9 10-all](https://user-images.githubusercontent.com/20047139/189287753-a77878f7-e924-44f9-bb07-9d5322e05119.png)

revanced-cli-2.9.10-all

![revanced-cli-2 10 0-all](https://user-images.githubusercontent.com/20047139/189287757-d8abc6c1-f2fa-4f1c-9287-ec5cae9fb939.png)

revanced-cli-2.10.0-all

![cache directory](https://user-images.githubusercontent.com/20047139/189296439-ab5fc616-50e3-40be-a94e-f75a5e045636.png)

cache directory

![inside cache directory](https://user-images.githubusercontent.com/20047139/189296514-377f4f4e-5bdf-43e5-8d15-df868b55f5d0.png)

Inside the cache directory

**Comment by oSumAtrIX** [comment]
That's most likely due to some process still holding the folder from being deleted, possibly aapt. Can you reproduce the issue?

**Comment by webzeroacs** [comment]
![failed](https://user-images.githubusercontent.com/20047139/189401933-09c2187d-844c-4c46-aa54-bc13bfd974f6.png)
I just built with all the latest files. The problem still occurs.

**Comment by webzeroacs** [comment]
![again](https://user-images.githubusercontent.com/20047139/189408079-1f83b37c-0566-4a8c-8d10-b3fd6d07e3e1.png)
I just rebooted and downloaded the latest files again and built a new one.
The problem continues to occur.
