### ISSUE TITLE
bug: appIconPath in options.toml

### ISSUE THREAD

**Issue by decipher3114** [revanced/revanced-cli#137]
### Type

Error while running the CLI

### Bug description

appIconPath not working

### Steps to reproduce

Everything in images

### Relevant log output

```shell
Everything in images
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/84389932/190312202-66b3ce14-8ef9-4d58-8938-6cfe795a201b.png)
![image](https://user-images.githubusercontent.com/84389932/190312213-a183dcba-7a08-4ebc-9ba4-f53588841722.png)

**Comment by Sculas** [comment]
It seems that you're using an incompatible version of patches and cli. Please update both to the latest version.

**Comment by decipher3114** [comment]
Everything on latest version, still the same error

**Comment by decipher3114** [comment]
![image](https://user-images.githubusercontent.com/84389932/190403494-8a8e3e7c-48f8-455d-9d35-4c5c57bd21cf.png)

See the error
![image](https://user-images.githubusercontent.com/84389932/190403516-676ad925-b8dd-4b6b-a2b4-ff140356339a.png)

see the options file
![image](https://user-images.githubusercontent.com/84389932/190403527-bdaec4ce-be35-4502-8ae5-6341f2f306a5.png)


here is the list of dir, everything latest
