### ISSUE TITLE
feat: Accept more than one patch using one `-i` flag

### ISSUE THREAD

**Issue by PolpOnline** [revanced/revanced-cli#138]
### Type

Other

### Issue

When you use the `-i` flag to re-include previously excluded patched using the `--exclusive` flag, you have to do something like this:
```
java -jar revanced-cli.jar [other flags] \
-i patch1 \
-i patch2 \
-i patch3
```
instead of this:
```
java -jar revanced-cli.jar [other flags] \
-i patch1,patch2,patch3
```

### Feature

Probably just set the command parser in a way to accept a comma-separated list for patches to include.

### Motivation

Because it's convenient, although this is a thing you will probably do once, many people will have to build their own patch list.

**Comment by oSumAtrIX** [comment]
By specification an option like `-i` is used to accept 1 parameter each time if you allow it multiple times. Technically you can make it a `--includedPatches` argument and then separately parse the argument as a comma separated array, though it is better to follow the standard and use `-i` for each patch.
