### ISSUE TITLE
feat: Instead of adding --with-options, add patch description to options.toml

### ISSUE THREAD

**Issue by decipher3114** [revanced/revanced-cli#139]
### Type

Cosmetic

### Issue

since --with-options is not a good idea to watch available options.
add description below the patch name and value

And all path options there, just set their value to null,

### Feature

appName = "YouTube"
# Changes App Name; Type: String; null not accepted
appIconPath = "null"
# Changes appIconPath; Type: String; null accepted

### Motivation

It will easier for users to edit that.

**Comment by oSumAtrIX** [comment]
TOML specs don't feature description of keys, only comments, and those can not be deserialized to a TOML file via the library. Additionally, not required settings should not be visible, TOML doesn't have null.

**Comment by decipher3114** [comment]
Then add default as for default value.
For users, it will be hard to manage.

**Comment by decipher3114** [comment]
Then add default as for default value.
For users, it will be hard to manage.

**Comment by decipher3114** [comment]
Then add default as for default value.
For users, it will be hard to manage.

**Comment by oSumAtrIX** [comment]
Users will use the manager, not the CLI
