### ISSUE TITLE
bug: Root Install Leads to Loop in Installing Shell

### ISSUE THREAD

**Issue by bassmadrigal** [ReVanced/revanced-cli#140]
### Type

Error while running the CLI

### Bug description

When running revanced cli and installing the root version of YouTube Revanced, once installed to the phone, the script just loops in my shell. Installation seems to go fine and the YouTube app works, but revanced-cli won't finish and will stay in a loop, showing the following 5 lines repeated about once a second:

```
09-16 23:33:26.691 30185 30185 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
09-16 23:33:26.695 30185 30185 I AndroidRuntime: Using default boot image
09-16 23:33:26.695 30185 30185 I AndroidRuntime: Leaving lock profiling enabled
09-16 23:33:26.777 30185 30185 D AndroidRuntime: Calling main entry com.android.commands.content.Content
09-16 23:33:26.788 30185 30185 D AndroidRuntime: Shutting down VM
```

I have to Ctrl+C to get out of it.

### Steps to reproduce

I ran the following command:

```
java -jar revanced-cli-2.10.1-all.jar \
    -a YouTube-17.33.42.apk \
    -c \
    -o revanced-youtube-17.33.42-root.apk \
    -b revanced-patches-2.57.0.jar \
    -m app-release-unsigned.apk \
    -d 1A111FDF600411 \
    --mount \
    -e microg-support \
```
(Revanced Integrations is at v0.36.6.)

I've been using revanced shortly after I updated my phone to 13.0 and my Vanced version broke, and I think my initial install was on 2 SEP and the issue has occurred the entire time.

### Relevant log output

```shell
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes8.dex
INFO: Writing resources...
INFO: Aligning revanced-YouTube-17.33.42-root_raw.apk to revanced-YouTube-17.33.42-root_aligned.apk
INFO: Copying revanced-YouTube-17.33.42-root_aligned.apk to revanced-YouTube-17.33.42-root.apk
INFO: Cleaned up cache directory
INFO: Installing by mounting
09-16 23:33:13.098 29662 29662 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
09-16 23:33:13.102 29662 29662 I AndroidRuntime: Using default boot image
09-16 23:33:13.102 29662 29662 I AndroidRuntime: Leaving lock profiling enabled
09-16 23:33:13.204 29662 29662 D AndroidRuntime: Calling main entry com.android.commands.content.Content
09-16 23:33:13.215 29662 29662 D AndroidRuntime: Shutting down VM
09-16 23:33:13.622 29814 29814 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
09-16 23:33:13.625 29814 29814 I AndroidRuntime: Using default boot image
09-16 23:33:13.625 29814 29814 I AndroidRuntime: Leaving lock profiling enabled
09-16 23:33:13.755 29814 29814 D AndroidRuntime: Calling main entry com.android.commands.content.Content
09-16 23:33:13.765 29814 29814 D AndroidRuntime: Shutting down VM
09-16 23:33:14.766 29937 29937 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
09-16 23:33:14.769 29937 29937 I AndroidRuntime: Using default boot image
09-16 23:33:14.769 29937 29937 I AndroidRuntime: Leaving lock profiling enabled
09-16 23:33:14.843 29937 29937 D AndroidRuntime: Calling main entry com.android.commands.content.Content
09-16 23:33:14.851 29937 29937 D AndroidRuntime: Shutting down VM
09-16 23:33:15.825 29966 29966 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
09-16 23:33:15.828 29966 29966 I AndroidRuntime: Using default boot image
09-16 23:33:15.828 29966 29966 I AndroidRuntime: Leaving lock profiling enabled
09-16 23:33:15.911 29966 29966 D AndroidRuntime: Calling main entry com.android.commands.content.Content
09-16 23:33:15.929 29966 29966 D AndroidRuntime: Shutting down VM
^C
```

**Comment by reisxd** [comment]
This isn't a bug but a feature to debug. See https://github.com/revanced/revanced-cli/blob/main/src/main/kotlin/app/revanced/utils/adb/Adb.kt#L99-L108

**Comment by bassmadrigal** [comment]
Good to know it isn't a bug. Is there an option to disable the loop? If not, is it something that can be added (or add an option to enable the debugging loop and keep it disabled by default)?

**Comment by decipher3114** [comment]
> 
Just Ctrl + C if youtube is successfully running

**Comment by bassmadrigal** [comment]
I'm aware of Ctrl+c, which is what I did to exit the loop (and documented above), but with no indication the loop is expected without reading (and understanding) the code, it makes the intentional loop feel like a bug.

Typically, debugging modes aren't default with software and they need to be enabled via flags or environment variables and rarely are they permanent without the option to disable. That was why I asked if it's possible to add an option to disable the loop (although, as I mentioned, debugging is typically disabled by default, so I think it'd make more sense to have an option to enable the debug loop).

**Comment by ViktorVoloshko** [comment]
After YT installed and running on phone (it should launch itself) just close YT and get rid of it in recent and loop should gone.

**Comment by bitingsock** [comment]
This prevents scripts from finishing
