### ISSUE TITLE
feat: Documentations 

### ISSUE THREAD

**Issue by nimagp** [revanced/revanced-cli#142]
### Type

Other

### Issue

The required parameters and files are a bit confusing.

### Feature

A simple documentation in `README.md` or Wikis.

### Motivation

For someone who is not an android developer, it's not that easy to understand the process.
And `<jar> --help` doesn't help much.  

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
--help shows a lost of all options and their description. Please mention which one is unclear.

**Comment by mushonnip** [comment]
maybe this is what you are looking for? https://github.com/revanced/revanced-documentation/wiki/Using-the-ReVanced-CLI-and-installing-ReVanced but yeah i agree that some readme file is needed

**Comment by nimagp** [comment]
Thanks.
