### ISSUE TITLE
feat: Show full package name when listing patches

### ISSUE THREAD

**Issue by gnuhead-chieb** [ReVanced/revanced-cli#157]
### Type

Other

### Issue

When I want to parse output of `java -jar cli-* -c -b patches-* -m integrations-* -a- -o- -l --with-versions --with-packages --with-descriptions`, `--with-packages` options only show last part of supported package name.
This makes it hard to know which package is supported.
In particular, Spotify and Youtube Music both end with "music" in the package name, so both are detected when "grep music" is performed.

### Feature

`--with-packages` options should be show full package name or unique identifier of app

### Motivation

​

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SebiAi** [comment]
This would be very nice for automation. +1
