### ISSUE TITLE
question: <Which java the client uses>

### ISSUE THREAD

**Issue by schooldanlp6** [revanced/revanced-cli#163]
### Type

Other

### Issue

So I have read carefully the documentation of the cli and launching it but couldnt find any information about the java version it needs. I only know its not java 8 

### Feature

which version of java does it use

### Motivation

because I want to run the cli

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The documentation mention the correct JDK version on the prerequisites page.
