### ISSUE TITLE
Broken mount scripts

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-cli#17]
Currently, mount scripts are being created for patched applications when they are deployed to a device. Rebooting the device shows, that the mount scripts do not work properly.

**Comment by Lucaskyy** [comment]
I believe Xinto mentioned this a while ago, that the `sleep` code works correctly on some phones, and on others, it doesn't.

**Comment by tillnelown** [comment]
> I believe Xinto mentioned this a while ago, that the `sleep` code works correctly on some phones, and on others, it doesn't.

I know a workaround for this,
> Magisk ships with a feature complete BusyBox binary (including full SELinux support). The executable is located at /data/adb/magisk/busybox

Instead of using the phones `sleep` run  `/data/adb/magisk/busybox sleep $x`

**Comment by oSumAtrIX** [comment]
Please PR this at line: https://github.com/revanced/revanced-cli/blob/a4ef47a28521f101c2fa71e423a0a39a5de8e2bf/src/main/kotlin/app/revanced/utils/adb/Constants.kt#L53

**Comment by Lucaskyy** [comment]
Actually, I don't think it was that. It's probably the phone setting `sys.boot_completed` to `1` while it's actually not 100% done, so it's probably a race condition on the phone.

**Comment by tillnelown** [comment]
> I believe Xinto mentioned this a while ago, that the `sleep` code works correctly on some phones, and on others, it doesn't.

This is not the case, Magisk already overwrites the path to sleep with its own implementation and therefore makes all phones use the same `sleep`.

**Comment by Sculas** [comment]
Just wondering because this issue was marked as completed without a message, but how was this fixed?
