### ISSUE TITLE
The app doesnt work

### ISSUE THREAD

**Issue by jonnykni** [revanced/revanced-cli#197]
### Type

Other

### Bug description

The app installs fine but when using it it keeps loading endlessly and doesn't play the videos.

### Steps to reproduce

I used youtube version 17.49.37
And the revaned manager
I also tested it with the cli
It all leads to the same result.

### Relevant log output

```shell
Idk
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Not an issue with CLI.
