### ISSUE TITLE
feat: ReVanced library [RFC]

### ISSUE THREAD

**Issue by Axelen123** [ReVanced/revanced-cli#207]
### Type

Functionality

### Issue

Using the patcher currently requires quite a lot of boilerplate. This has resulted in substantial code duplication in the Manager and CLI codebases.

### Feature

Turn the CLI backend into it's own library and use that for the CLI and Manager.

This is just an idea on how the API could like to get things going, but suggestions are welcome:
```kt
data class Options(
  val logger: Logger,
  ......
)

class Session/Patcher(private val Options) {
  fun addPatches(patches: Iterable<Class<out patcher.Patch>>)
  fun addIntegrations(integrations: List<File>, callback: (File) -> Unit)
  fun execute(patches: PatchConfiguration, input: File, output: File): PatcherResult
}
```

- Should the library deal with signing at all? (Edit: Yes)
- How should users of the library specify what patches to use and their options?
- How should the users load patch bundles?

### Motivation

This will reduce code duplication and make the patcher much easier to use due to requiring less boilerplate.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Axelen123** [comment]
@oSumAtrIX @codingPotato21

**Comment by oSumAtrIX** [comment]
The library should include signing, aligning, and deployment of APKs as well provide an interface between the patcher and the frontend application which is using the library

**Comment by Axelen123** [comment]
I believe we should just start with a standard kotlin library, but other methods of interfacing with it can be looked into in the future as well.

**Comment by decipher3114** [comment]
Planning is good, but "only planning" is not so good. Proceed with something, be it anything. Do it.

**Comment by reisxd** [comment]
> Planning is good, but "only planning" is not so good. Proceed with something, be it anything. Do it.

If you really want to, you can create the library in this state. Note that you'll get headaches while people telling you that "this shouldn't be like this" or "change this to this".

**Comment by Axelen123** [comment]
> The library should include signing, aligning, and deployment of APKs as well provide an interface between the patcher and the frontend application which is using the library

I believe the deployment API could maybe look something like this:
```kt
interface Installer {
   fun install(apk: File)
}

class AndroidInstaller {
   fun install(apk: File) {
      TheNativeAndroidAPIForDoingThis(apk)
   }
}

class AndroidRootInstaller {
    fun install(apk: File) {
       ....
   }
}

class AdbInstaller {
   fun install(apk: File) {
       exec("adb install $filepath")
   }
}
```

**Comment by oSumAtrIX** [comment]
The split branch already features similar abstraction between root and non root installation.

**Comment by Axelen123** [comment]
> The split branch already features similar abstraction between root and non root installation.

Good. Do you think we should rebase that branch?

**Comment by oSumAtrIX** [comment]
Yeah split is rebased time to time

**Comment by decipher3114** [comment]
What if we don't implement the installer at all in the library ??

Android installer only in APP and ADB installer only in CLI

**Comment by oSumAtrIX** [comment]
The DI pattern can be used for that, this isn't a problem

**Comment by oSumAtrIX** [comment]
Currently, the library supports options, signing, aligning, and installation. ReVanced Patcher-related code is not included due to redundancy because the preferred API in the issue description is already present in ReVanced Patcher. Users of the library would have to depend on ReVanced Patcher too though, which is not ideal. Instead, the library should act as the abstraction layer to interface to ReVanced Patcher ideally. This would require mirroring the API of ReVanced Patcher in the library.
