### ISSUE TITLE
feat: Backup or download settings

### ISSUE THREAD

**Issue by Mimicthis** [revanced/revanced-cli#214]
### Type

Functionality

### Issue

Please add a option to save YouTube Revanced settings, back them up or download as file to device etc. 

### Feature

It solves the issue of need to adjust every setting from countless. 

### Motivation

Convienece. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This has nothing to do with ReVanced CLI.
