### ISSUE TITLE
feat: exclude multiple patches in one option

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [revanced/revanced-cli#223]
### Type

Functionality

### Issue

typing `-e` for every patches makes the command unneccessarily long

### Feature

when using `--exclude=<patch>`, allow selection of multiple patches separated w/ comma. Example: `--exclude='always-autorepeat,disable-auto-captions,wide-searchbar,premium-heading'`

### Motivation

this makes the command shorter.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is  unconventional. The syntax is controlled by the underlying CLI parser.
