### ISSUE TITLE
bug: `jar` file not available for latest dev release

### ISSUE THREAD

**Issue by johnconner122** [ReVanced/revanced-cli#243]
### Type

Other

### Bug description

No `jar` file available for latest dev release.

### Steps to reproduce

.

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
Still no jar file!!!

**Comment by oSumAtrIX** [comment]
Fixed.

**Comment by cyberboh** [comment]
> Fixed.

The release version isn't same with the release tittle
![image](https://github.com/ReVanced/revanced-cli/assets/99109969/c58b05a5-97bb-4542-a70a-ddd2c15e154f)
Does both actually dev.4?

**Comment by oSumAtrIX** [comment]
Fixed.

**Comment by cyberboh** [comment]
@oSumAtrIX `.jar` file not available for version 4.0.0 , maybe you can fix it
