### ISSUE TITLE
feat: Abort patching if the app version is incompatible

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-cli#246]
### Type

Functionality

### Issue

CLI still continue patching process eventhough the version is incompatible. it should stopped if the version missmatch
See
![image](https://github.com/ReVanced/revanced-cli/assets/99109969/a1e6e5a2-ac8b-45b0-bdfc-dfb87650e6bc)

### Feature

CLI should stop patching if the version is missmatched

### Motivation

Patching software with mismatched versions could potentially lead to data corruption or inconsistencies. If the patch is designed to work with a specific version, applying it to a different version might not guarantee that the changes will be properly integrated. By stopping the patching process, you could prevent potential data issues that arise from version incompatibilities. Allowing patching with mismatched versions could confuse users and create a poor user experience. Users might expect that patching only works with compatible versions, and if they encounter errors due to version mismatches, it could lead to frustration and confusion.
Also, we can reduce time of patching process.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
If you do not enable the experimental flag, it does not apply patches to a version that's incompatible.

**Comment by cyberboh** [comment]
> If you do not enable the experimental flag, it does not apply patches to a version that's incompatible.

I never use that flag
See my command parameter on the image above. It is just regular flag to patching.

**Comment by reisxd** [comment]
> I never use that flag

Then the patches that are incompatible don't get applied. As simple as that.

**Comment by cyberboh** [comment]
> > I never use that flag
> 
> Then the patches that are incompatible don't get applied. As simple as that.

I know it won't applied, but patching process should stopped after checked the app version and found incompatible version to reduce patching time

**Comment by reisxd** [comment]
What if only a single patch is incompatible with the version, will it also abort the patching process?

**Comment by oSumAtrIX** [comment]
Breaking execution does not happen for the same reason it does not in #244. ReVanced CLI automatically checks the compatibility annotation and filters out patches that are not compatible from supplying them to ReVanced Patcher. The experimental CLI option bypasses that thought.
