### ISSUE TITLE
bug: --include parameter is always ignored

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-cli#247]
### Type

Error while running the CLI

### Bug description

Using latest dev release, the -i flag appears to always be ignored

### Steps to reproduce

Patch using CLI dev release, try including a normally excluded patch.

### Relevant log output

```shell
java -jar revanced-cli-*-all.jar patch --patch-bundle revanced-patches*.jar -m revanced-integrations*.apk --out revanced.apk youtube*.apk -i enable-android-debugging 
INFO: Loading patches 
INFO: Setting patch options 
INFO: Resolving classes using existing cache 
INFO: Decoding app manifest 
INFO: Enable android debugging excluded by default
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by uvzen** [comment]
> Maybe I'm overlooking something?

I have that problem too. I tried to include the "custom branding" patch which was disabled by default in the dev cli but it is ignored.

**Comment by Ushie** [comment]
@oSumAtrIX This issue is still around in v3.0.1

```
java -jar revanced-cli-3.0.1-all.jar patch -b revanced-patches-2.189.0.jar -m revanced-integrations-0.117.0.apk -o out.apk -i custom-branding input.apk
INFO: Loading patches
INFO: Setting patch options
INFO: Decoding app manifest
INFO: Change package name excluded by default
INFO: Compact header excluded by default
INFO: Custom branding excluded by default
```

**Comment by oSumAtrIX** [comment]
Heh, I love phantom fixes..

**Comment by Ushie** [comment]
Maybe this issue can be re-opened for the time being

**Comment by souravdas142** [comment]
> Heh, I love phantom fixes..

But that wasted my 1 hour until I found this. :smile:
