### ISSUE TITLE
Bug: CLI v3.0.0 doesn't work

### ISSUE THREAD

**Issue by Narcissu-Moschus** [ReVanced/revanced-cli#249]
### Type

Error while running the CLI

### Bug description

What changes have been made with CLI v3.0.0?
I cannot use it to build apks.
I tried "-h", "--help" and "-hV" but none of the instructions worked.

### Steps to reproduce

revanced-cli-v3.0.0.jar
revanced-patches-v2.188.1.jar
revanced-integrations-v0.116.2.apk

### Relevant log output

```shell
D:\Application\Android\ReVanced\revanced>java -jar revanced-cli-v3.0.0.jar -b revanced-patches-v2.188.1.jar -m revanced-integrations-v0.116.2.apk -a "YouTube 18.32.39.apk" -c -o "YouTube 18.32.39 (RV 2.188.1-0.116.2).apk"
Unknown options: '-b', 'revanced-patches-v2.188.1.jar', '-m', 'revanced-integrations-v0.116.2.apk', '-a', 'YouTube 18.32.39.apk', '-c', '-o', 'YouTube 18.32.39 (RV 2.188.1-0.116.2).apk'
Usage: revanced-cli [-hV] [COMMAND]
Command line application to use ReVanced
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  list-patches  List patches from supplied patch bundles
  patch         Patch the supplied APK file with the supplied patches and
                  integrations
  options       Generate options file from patches
  utility       Commands for utility purposes
```

### Screenshots or videos

![image](https://github.com/ReVanced/revanced-cli/assets/63994364/5f8251c5-453a-4f8e-a7a4-66fe2eda6ce8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cyberboh** [comment]
missing `patch` argument
see https://github.com/ReVanced/revanced-cli/blob/main/docs/1_usage.md

**Comment by oSumAtrIX** [comment]
Your arguments are incorrect
