### ISSUE TITLE
bug: Create custom keystore

### ISSUE THREAD

**Issue by NoelJacob** [ReVanced/revanced-cli#252]
### Type

Error while running the CLI

### Bug description

I create custom keystore like this but ` keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath "./bcprov-jdk15on-1.70.jar" -storetype BKS -keyalg RSA -keysize 2048 -validity 9999 -dname "CN=Android Debug,O=Android,C=US" -keypass android ` the cli shows error.

Solution would be to either give a command for creating custom keystore with keytool or expose a utility function that can generate keystore with predefined defaults without impacting security (prefered). Sadly, I don't have the Kotlin expertise to do that but it looks trivial enough.

### Steps to reproduce

 ` keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -storepass android -provider org.bouncycastle.jce.provider.BouncyCastleProvider -providerpath "./bcprov-jdk15on-1.70.jar" -storetype BKS -keyalg RSA -keysize 2048 -validity 9999 -dname "CN=Android Debug,O=Android,C=US" -keypass android `

### Relevant log output

```shell
Will provide later, tired of debugging :)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Where is the error
