### ISSUE TITLE
bug: CLI is showing default excluded patches, no matter what the package name is

### ISSUE THREAD

**Issue by GeekCornerGH** [ReVanced/revanced-cli#256]
### Type

Other

### Bug description

Just while patching

### Steps to reproduce

For the record, I'm using ReX, but since it switched to official CLI/Manager, then it's not a ReX bug

1. Grab YouTube Music apk (in my case)
2. Patch it using default patches (ReX in my case)
3. Check output

### Relevant log output

```shell
INFOS: Loading patches
INFOS: Setting patch options
INFOS: Decoding app manifest
INFOS: Add splash animation excluded by default
INFOS: Custom branding icon MMT excluded by default
INFOS: Custom branding icon MMT excluded by default
INFOS: Custom branding icon Revancify red excluded by default
INFOS: Custom branding icon Revancify red excluded by default
INFOS: Disable landscape mode excluded by default
INFOS: Enable debug logging excluded by default
INFOS: Enable debug logging excluded by default
INFOS: Force hide player button background excluded by default
INFOS: Force premium heading excluded by default
INFOS: Hide double tap overlay filter excluded by default
INFOS: MaterialYou excluded by default
INFOS: Optimize resource excluded by default
INFOS: Merging integrations
INFOS: Deleting existing resource cache directory
INFOS: Decoding resources
```

### Additional context

MaterialYou is a YouTube only patch, not a YouTube music patch. It sholdn't even be in the log at all

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by GeekCornerGH** [comment]
Thanks osum for the quick fix

**Comment by kazimmt** [comment]
Yay, It's Fixed Now!

![](https://github.com/ReVanced/revanced-cli/assets/82371061/6b38205c-70c3-49f8-814d-2fd01326a90d)

**Comment by Ushie** [comment]
This can be closed now

**Comment by GeekCornerGH** [comment]
I suggest to keep it open until dev is merged to main

**Comment by Ushie** [comment]
No, we don't, I thought dev was merged already, my bad
