### ISSUE TITLE
feat(list-patches): scope per package flag

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-cli#261]
### Type

Functionality

### Issue

Currently, there's no way to filter the list-patches output to only show the patches relevant to a specific app

### Feature

Add a --for-package flag which can take an APK (to parse the package name from) or take a package name directly, which would then ensure that the output is only relevant to that package

### Motivation

It makes it easier to find the patches for the app I'm trying to patch without having to go through a huge list of unrelated patches, --with-packages flag isnt much help because it simply contributes to spam and you have to pay attention and group which patches have the package name you're aiming for

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
@oSumAtrIX If you don't have anything against the proposed solution, I may open a PR once given the green light

**Comment by oSumAtrIX** [comment]
The option can be named `--filter-package` that accepts a package name to filter patches. A PR sounds good.

**Comment by Ushie** [comment]
Accepting APK aswell shouldn't be a problem, right?

**Comment by oSumAtrIX** [comment]
The package name should suffice, it's the most straight forward and intuitive approach. Don't forget to push the docs too
