### ISSUE TITLE
feat: (sign apk) Is it possible to add a  feature to signapk/change signature with command like  --sign-apk

### ISSUE THREAD

**Issue by dib12** [ReVanced/revanced-cli#264]
### Type

Functionality

### Issue

Help to change signature

### Feature

Help to change signature

### Motivation

Help to change signature

### Additional context

Help to change signature

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by Ushie** [comment]
It can be added as a utility, but what is the usage scenario and motivation for this? what's stopping you from using apksigner

**Comment by oSumAtrIX** [comment]
A --resign option along the install subcommand can be added.

**Comment by ghost** [comment]
![IMG_20230914_203301_927](https://github.com/ReVanced/revanced-cli/assets/61652361/e82b333d-10bb-4553-a5d9-14d357bafee6)

Revanced built yt with unused resources without removing them To remove unused files and to resign

Also to sign mmicrog with same signature of yt.

U can add the features. If u want

**Comment by oSumAtrIX** [comment]
ReVanced CLI has nothing to do with YT, mmicrog, the patcher or removing unused files

**Comment by ghost** [comment]
Is there any way to sign with testkey.x509.pem ,testkey.pk8 
Only .key store support

With this there is no play protect warning like "unsafe app blocked" etc

**Comment by oSumAtrIX** [comment]
The warning is shown once, you can try and see.

**Comment by ghost** [comment]
@oSumAtrIX Why u reopened the issue !?
I got a way to clean unused resources(70mb+)
After resource complile and before app align i just remove unused through zip command.
zip -d input.apk "res/*" "lib/x86*" "lib/armeabi*"
And it align and sign apk without any issue and decrease app size to 68mb

**Comment by oSumAtrIX** [comment]
I reopened to track this feature for ReVanced CLI
