### ISSUE TITLE
bug: --exclusive subcommand ignores included patches

### ISSUE THREAD

**Issue by InakiArzalluz** [ReVanced/revanced-cli#273]
### Type

Error at runtime

### Bug description

running the `patch` command with the `--exclusive` subcommand excludes all available patches, despite some patches being explicitly included using `-i`

### Steps to reproduce

1. Download:
    - CLI v4.0.0-dev.2
    - Patches v2.191.0-dev.14
    - Integrations v0.118.0-dev.12

2. Run:
`java -jar "revanced-cli-4.0.0-dev.2-all.jar" patch --patch-bundle "revanced-patches-2.191.0-dev.14.jar" --out output.apk -m "revanced-integrations-0.118.0-dev.12.apk" --exclusive -i sponsorblock -i vanced-microg-support "com.google.android.youtube_18.32.39.apk"`

### Relevant log output

```shell
no relevant log output outside from what is shown in the following screenshot.
```

### Screenshots or videos

Vanced-microg-support is being excluded too, but it's far down on the list

![Captura de pantalla 2023-09-26 134456](https://github.com/ReVanced/revanced-cli/assets/65030772/fd3a10de-d0c1-4d97-a86c-91cf29a1564a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Casing is not ignored.
