### ISSUE TITLE
feat: List flag of patch when using list-patches

### ISSUE THREAD

**Issue by GieltjE** [ReVanced/revanced-cli#274]
### Type

Functionality

### Issue

```
java -jar revanced-cli-4.0.0-dev.3-all.jar list-patches --with-packages --with-versions --with-options --with-descriptions --filter-package-name=com.google.android.youtube revanced-patches-2.191.0-dev.22.jar
```
Will output something like
```
Name: Hide endscreen cards
Compatible packages:
        Package name: com.google.android.youtube
        Compatible versions:
```
While the patch command requires something like ```-e hide-endscreen-cards``` (if that's even still correct)

### Feature

List the parameter name of the patch for usage with the patch command

### Motivation

Would solve some confusion and make everyones life easier as it's currently quite hard to figure out how to [in/ex]clude a specific patch

### Additional context

Not sure if this should be here as a cli request or in the revanced-patches repo, correct me if it should be over there.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not sure what you mean, a list command already exists

**Comment by GieltjE** [comment]
The list command does not return the parameter that needs to be used for the patch command e.g. 'hide-endscreen-cards'

**Comment by Ushie** [comment]
Utilisation is specified in the docs and help command

You can include patches by doing `-i "Hide endscreen cards"`
