### ISSUE TITLE
Remove `-a` and `-o` required arguments when listing available patches `-l`

### ISSUE THREAD

**Issue by n0k0m3** [revanced/revanced-cli#28]
Doesn't make sense if `-a` and `-o` are required when the only thing `cli` will read is file from `-b`.

**Comment by oSumAtrIX** [comment]
The cli reads the apk with -a writes to -o and gets the patch bundles from -b. Not sure what you mean

**Comment by CnC-Robert** [comment]
> The cli reads the apk with -a writes to -o and gets the patch bundles from -b. Not sure what you mean

He means when you list the patches you dont need a youtube apk or output file
