### ISSUE TITLE
bug: How to include the patches to be applied?

### ISSUE THREAD

**Issue by juniosxs** [ReVanced/revanced-cli#286]
### Bug description

Before I included the patches to be applied as follows below but this seems to no longer work in the new Revanced cli

-i spoof-wifi-connection \
-i hide-ads \
-i video-ads \
-i external-downloads \
-i premium-heading \
-i hide-player-buttons \
-i remove-player-controls-background \
-i sponsorblock \
-i disable-shorts-on-startup \
-i theme \
-i client-spoof \
-i open-links-externally \
-i vanced-microg-support \
-i minimized-playback \
-i hdr-auto-brightness \
-i remember-video-quality

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch names are incorrect.

**Comment by juniosxs** [comment]
Could you tell me what the name format is for the name of the patches?

**Comment by SangeethSujith** [comment]
its weird now  we have to do it like this
-i "Custom branding"
i dont know why they had to do this but this is just plain bad
