### ISSUE TITLE
bug: how to apply only specific patches?

### ISSUE THREAD

**Issue by juniosxs** [ReVanced/revanced-cli#287]
### Bug description

how can I only apply specific patches? Previously with revanced-cli v3.x.x it was possible to do this with i- patch-name commands but this doesn't seem to work anymore in the new revanced-cli 4.x.x

Could you show an example of how to apply only specific Patches that I want.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Here you go: https://github.com/ReVanced/revanced-cli/blob/dev/docs/1_usage.md

**Comment by exzhawk** [comment]
> Here you go: https://github.com/ReVanced/revanced-cli/blob/dev/docs/1_usage.md

I didn't get it. When I ran the cli with following command, to apply only one patch,
```bash
java -jar revanced-cli.jar patch \
        --patch-bundle revanced-patches-4.3.0-dev.11.jar \
        --merge revanced-integrations-1.4.0-dev.7.apk \
        --include "Bypass URL redirects" \
        'com.google.android.youtube_19.04.37-1544154560_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk'
```
I got
```
INFO: Loading patches            
INFO: Decoding app manifest          
INFO: Enable slide to seek excluded 
INFO: Change header excluded    
INFO: Custom branding excluded      
INFO: Remove player controls background excluded 
INFO: Change package name excluded     
INFO: Override certificate pinning excluded  
INFO: Enable Android debugging excluded 
INFO: Remove screen capture restriction excluded 
INFO: Export all activities excluded     
INFO: Predictive back gesture excluded 
INFO: Spoof SIM country excluded 
INFO: Remove screenshot restriction excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Setting patch options     
INFO: Merging integrations                                                            
INFO: Deleting existing resource cache directory 
INFO: Decoding resources               
INFO: Executing patches             
INFO: Alternative thumbnails succeeded 
INFO: Always repeat succeeded              
INFO: Announcements succeeded 
INFO: Bypass URL redirects succeeded 
INFO: Change start page succeeded 
```
Is that mean `Alternative thumbnails` is also applied? Is there a way to exclude all patches except the one I specified?
