### ISSUE TITLE
bug: formatting error when reading patch names

### ISSUE THREAD

**Issue by juniosxs** [ReVanced/revanced-cli#288]
### Bug description

an example the name of the patch below

Vanced MicroG support

cannot be used like this 

-i Vanced MicroG support
because it does not recognize the space, and if you put the dash, the patch is not recognized, it is only recognizing patches that are unique names without spaces, for example like this 

-i SponsorBlock

any patch that does not have a unique name is not being recognized, for example if I use the following patches none will be recognized.

-i Hide ads -i Video ads -i External downloads

however, if I use the following patches in the same way, they are recognized and applied

-i SponsorBlock -i Theme

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by juniosxs** [comment]
INFO: SponsorBlock succeeded
INFO: Theme succeeded
INFO: Compiling modified dex files

As you can see, only patches with a single name without spaces are being read and applied.

**Comment by oSumAtrIX** [comment]
You can input spaces with quotes

**Comment by juniosxs** [comment]
Great, it worked like that, thanks

**Comment by khuldraeseth** [comment]
That does not work with tools like GNU Make that treat spaces as separators. Why were the patch names changed to include spaces in the first place?

**Comment by Ushie** [comment]
> Why were the patch names changed to include spaces in the first place?

Because that makes the most sense, ReVanced CLI isn't the only patching client, the end user is expected to use a GUI client where this format is the most fitting and natural

I do disagree with the way ReVanced CLI handles the patch names, I don't like the undocumented case sensitivity for example

**Comment by oSumAtrIX** [comment]
Spaces in quotes are eligible strings for GNU tools. PicoCLI is following POSIX conventions to parse the CLI input.

Apart from that you can use indices.
