### ISSUE TITLE
bug: `revanced-cli-4.0.2`: Missing mount script in `/data/adb/service.d` and apk in `/data/adb/revanced` after mounting

### ISSUE THREAD

**Issue by exconvinced** [ReVanced/revanced-cli#293]
### Bug description

Tried installing a patched APK (e.g., YouTube) onto a rooted phone by mounting. I observe that [`revanced-cli-4.0.2`](https://github.com/ReVanced/revanced-cli/releases/tag/v4.0.2) does not create these objects:
- patched apk `com.package.apk` in `/data/adb/revanced`. Only the folder is created.
- mount script `mount.sh` in `/data/adb/service.d`. No folder is created.
 
Nonetheless, the CLI invokes the app, so you'll see the app launch on your phone but it would be the stock app without patches.

The good news is mounting with [`revanced-cli-3.1.0`](https://github.com/ReVanced/revanced-cli/releases/tag/v3.1.0) works fine. Temporarily, I'm using this version for mounting purposes.

Below is the logcat when the mounting was ongoing.

### Error logs

```shell
10-21 19:07:57.213 13536 13536 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:07:57.218 13536 13536 I AndroidRuntime: Using default boot image
10-21 19:07:57.218 13536 13536 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:07:57.220 13536 13536 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:07:57.220 13536 13536 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:07:57.436 13536 13536 D AndroidRuntime: Calling main entry com.topjohnwu.superuser.internal.RootServerMain
10-21 19:10:18.547 14917 14917 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:18.551 14917 14917 I AndroidRuntime: Using default boot image
10-21 19:10:18.551 14917 14917 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:18.553 14917 14917 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:18.553 14917 14917 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:18.707 14917 14917 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:18.728 14917 14917 D AndroidRuntime: Shutting down VM
10-21 19:10:44.089 15054 15054 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.092 15054 15054 I AndroidRuntime: Using default boot image
10-21 19:10:44.092 15054 15054 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.094 15054 15054 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.094 15054 15054 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.138 15057 15057 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.152 15057 15057 I AndroidRuntime: Using default boot image
10-21 19:10:44.152 15057 15057 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.155 15080 15080 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.158 15080 15080 I AndroidRuntime: Using default boot image
10-21 19:10:44.158 15080 15080 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.159 15080 15080 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.159 15080 15080 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.160 15057 15057 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.160 15057 15057 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.231 15093 15093 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.234 15093 15093 I AndroidRuntime: Using default boot image
10-21 19:10:44.234 15093 15093 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.236 15093 15093 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.236 15093 15093 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.288 15072 15072 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.290 15072 15072 I AndroidRuntime: Using default boot image
10-21 19:10:44.290 15072 15072 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.291 15072 15072 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.291 15072 15072 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.317 15080 15080 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.347 15099 15099 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.350 15099 15099 I AndroidRuntime: Using default boot image
10-21 19:10:44.350 15099 15099 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.359 15099 15099 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.359 15099 15099 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.360 15080 15080 D AndroidRuntime: Shutting down VM
10-21 19:10:44.363 15090 15090 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
10-21 19:10:44.371 15090 15090 I AndroidRuntime: Using default boot image
10-21 19:10:44.371 15090 15090 I AndroidRuntime: Leaving lock profiling enabled
10-21 19:10:44.376 15090 15090 D AndroidRuntime: addProductProperty: pBrand1 is not null
10-21 19:10:44.376 15090 15090 D AndroidRuntime: addProductProperty: not brand or 7
10-21 19:10:44.442 15054 15054 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.468 15054 15054 D AndroidRuntime: Shutting down VM
10-21 19:10:44.516 15057 15057 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.519 15093 15093 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.532 15099 15099 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.568 15093 15093 D AndroidRuntime: Shutting down VM
10-21 19:10:44.572 15099 15099 D AndroidRuntime: Shutting down VM
10-21 19:10:44.573 15072 15072 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.577 15057 15057 D AndroidRuntime: Shutting down VM
10-21 19:10:44.594 15072 15072 D AndroidRuntime: Shutting down VM
10-21 19:10:44.617 15090 15090 D AndroidRuntime: Calling main entry com.android.commands.content.Content
10-21 19:10:44.627 15090 15090 D AndroidRuntime: Shutting down VM
```

### Additional context

The mobile device is running Android 11 with Magisk 26.1.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Did you grant ReVanced CLI/ Shell root access?

**Comment by exconvinced** [comment]
Nice approach! Sure, on with the basics: Yep, my `adb` shell has been authorized already (I checked on Magisk). Also, the `--mount` flag is there when I executed the command:
```bash
java -jar revanced-cli.jar utility install --mount com.package.name -a com.package.apk adb-device-serial-number
```

**Comment by oSumAtrIX** [comment]
I can not reproduce the issue. Can you debug it on your end? If so, check, if you get stuck anywhere in the function here: https://github.com/ReVanced/revanced-library/blob/fda3eca74f30b968d8ee816d63a3dcf493e026de/src/main/kotlin/app/revanced/library/adb/AdbManager.kt#L75

**Comment by exconvinced** [comment]
I can try. But I haven't touched Kotlin before. Let me get back to you on this maybe after next week.

**Comment by exconvinced** [comment]
I got lost at Step 3 in [setting up the IntelliJ IDEA Environment](https://github.com/ReVanced/revanced-documentation/blob/main/docs/revanced-development/1_setup_development_environment.md#3-%EF%B8%8F-setup-intellij-idea). I can't figure out how to do this:
> 3. Add a new Run/Debug configuration for the revanced-cli project; Make sure to add Before launch tasks to build revanced-patches and optionally publish revanced-patcher

Do I create this `xml` file manually or is there a way in IntelliJ IDEA? What filename do I use? How to execute it? Do I place it in the root of `revanced-cli`?

**Comment by exconvinced** [comment]
I know, but I don't see an XML file format in the drop-down list:

![image](https://github.com/ReVanced/revanced-cli/assets/139973199/482540d3-b358-4860-b5ee-92158ec51121)

**Comment by oSumAtrIX** [comment]
I suggest to get familiar with the IDE first:

https://www.jetbrains.com/help/idea/run-debug-configuration.html

**Comment by exconvinced** [comment]
Got it bro. But turns out I just need to tick this so I can see the config file in the project directory😩
![image](https://github.com/ReVanced/revanced-cli/assets/139973199/7756ab53-0377-44c2-a317-a254ecf6550e)

**Comment by exconvinced** [comment]
I finished writing the run/debug config. I'll add an adb device parameter later:

```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run ReVanced CLI" type="JetRunConfigurationType">
    <option name="MAIN_CLASS_NAME" value="app.revanced.cli.command.MainCommand.kt" />
    <module name="revanced-cli.main" />
    <option name="PROGRAM_PARAMETERS" value="
             patch
             -b ../revanced-patches/build/libs/revanced-patches-2.196.0-dev.11.jar
             -m ../revanced-integrations.apk'
             -o ../revanced.apk
             ../unpatched.apk

    "/>
    <method v="2">
      <option name="RunConfigurationTask" enabled="true" run_configuration_name="revanced-patcher [publish]" run_configuration_type="GradleRunConfiguration" />
      <option name="RunConfigurationTask" enabled="true" run_configuration_name="revanced-patches [build]" run_configuration_type="GradleRunConfiguration" />
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>
```

I just want to be able to run this successfully, but it won't just yet. What class name do I put here?

![image](https://github.com/ReVanced/revanced-cli/assets/139973199/83d3e8fd-4fde-44c6-8b43-e91057504def)

**Comment by oSumAtrIX** [comment]
As the documentation as well as the sample XML suggests, the Main command class

**Comment by oSumAtrIX** [comment]
The class is present: https://github.com/ReVanced/revanced-cli/blob/a8c86821161e1a0392e93d92934597966146ab28/src/main/kotlin/app/revanced/cli/command/MainCommand.kt#L11

You may need to sync the project files with Gradle or troubleshoot your IDE

**Comment by exconvinced** [comment]
You're correct, I can confirm the .kt file is in that exact directory. I need to figure something out... I'll get back to you

**Comment by exconvinced** [comment]
I honestly don't know what the problem is. Here's what I've been doing:

0. Clone all `revanced` dev repos. Each repo will be stored in their dedicated folders locally.

1. Run `gradlew build` inside `revanced-cli`, `revanced-patcher`, and `revanced-patches`. (I skipped building `revanced-integrations` since I already have an apk.)

2. Open `revanced-cli` folder in IntelliJ IDEA. Go to `Project Structure > Modules` then import `revanced-patches` folder as module. Just click `Next` > `Next` > `Next` > `Next` > `Create`.

3. Back to the main project window, create a `Run/Debug Configuration` file (this will create an XML file in `revanced-cli/.run` folder. Using the sample XML, modify the `value` of the `PROGRAM_PARAMETERS`. IDEA should then be able to recognize that the script depends on `Kotlin SDK` and the `MAIN_CLASS_NAME` being `app.revanced.cli.command.MainCommand.kt`.

And then the error happens when the XML is run:
> ![image](https://user-images.githubusercontent.com/139973199/279628395-691359ac-87cf-4e93-9de8-14b74021fc6a.png)

If you have any ideas, please tell me. I'm not proficient at all in Gradle/Kotlin/IntelliJ IDEA, let alone troubleshooting this error.

**Comment by oSumAtrIX** [comment]
If you can see a Run button in the line I sent, you can click on it. The IDE will automatically create a run configuration

**Comment by exconvinced** [comment]
Whohoo it's working now!

![image](https://github.com/ReVanced/revanced-cli/assets/139973199/ab57b98d-b7ec-4c51-9978-bcbd6cc10812)

**Comment by exconvinced** [comment]
I can now run `revanced-cli` in IDEA. I tested two methods of mounting a patched apk:
- Patching a stock apk via `patch` and mounting it with `--mount` flag, all in one go.
- Using `utilities` to mount an already patched apk with `--mount` flag.
The IDE didn't raise an error.

Unlike in my initial issue, the patched apk now gets written in `/data/adb/revanced`. However, the mount shell script does not get created in `/data/adb/service.d` if this folder is not present.

**Comment by oSumAtrIX** [comment]
In which scenario would that folder not be present?

**Comment by exconvinced** [comment]
When I delete the folder itself (I thought it'd be faster than running the unmount command in cli).

**Comment by oSumAtrIX** [comment]
I don't think ReVanced has to handle this case. You are not supposed to delete folders in your file system and programs should be able to assume they exist for that reason. Though, if you want, you can PR handling this case in the ReVanced Library repository. If there is anything else, please reopen this issue

**Comment by Ushie** [comment]
I don't see how this is better fit in revanced library instead of here..

**Comment by oSumAtrIX** [comment]
Because the mounting code (AdbManager) is in ReVanced Library.

**Comment by Ushie** [comment]
> Because the mounting code (AdbManager) is in ReVanced Library.

I see
