### ISSUE TITLE
bug: "INFO: " gets prepended to the output of `list-patches` command

### ISSUE THREAD

**Issue by SandaruKasa** [ReVanced/revanced-cli#303]
### Bug description

The title says it.

### Solution

I tried replacing logging with a simple `println` in #301, but that was rejected.

Sadly, I am not too familiar with logging in Java, so I do not know how to suppress this "INFO: " prefix & whether it is possible at all.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a bug. The logger is used to output anything, and in this case, it is logging "info". I believe the correct way would be to configure the logger output format through other means.
