### ISSUE TITLE
patched reddit won't open bug: 

### ISSUE THREAD

**Issue by Awmid** [ReVanced/revanced-cli#306]
### Bug description

i tried patching reddit but after i installed it i couldnt open it although i could patch youtube successfully before and i did the same. i also tried patching it with revanced manager on android but still doesnt open.
on windows it shows this  error "SEVERE: Failed to delete existing resource cache directory":

java -jar revanced-cli-4.3.0-all.jar patch -b revanced-patches-2.202.0.jar -m revanced-integrations-0.125.0.apk -o out.apk reddit.apk
INFO: Loading patches
INFO: Decoding app manifest
INFO: Export all activities excluded
INFO: Remove screen capture restriction excluded
INFO: Spoof SIM country excluded
INFO: Change package name excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Remove screenshot restriction excluded
INFO: Predictive back gesture excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Disable screenshot popup succeeded
INFO: Hide ads succeeded
INFO: Sanitize sharing links succeeded
INFO: Unlock premium Reddit icons succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiled classes9.dex
INFO: Compiled classes10.dex
INFO: Compiled classes11.dex
INFO: Compiled classes12.dex
INFO: Compiling modified resources
INFO: Aligning reddit.apk
INFO: Signing reddit.apk

and this is revanced manager log:
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: M2006C3MII
Android version: 10
Supported architectures: armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2023.49.1
Patches version: v2.202.0
Patches added: Disable screenshot popup, Hide ads, Sanitize sharing links, Unlock premium Reddit icons
Patches removed: Hide ads, Disable screenshot popup, Unlock premium Reddit icons, Sanitize sharing links
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
Installed!

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You are patching a split APK file but need a full one
