### ISSUE TITLE
feat: Interactive shell script

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-cli#307]
### Feature description

Add bash and CMD scripts that simplify and automate the usage of ReVanced CLI.

### Motivation

Scripts will simplify the usage and improve automation. This will be useful in environments where a short setup is necessary to use ReVanced CLI.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by gim-** [comment]
Yes, some ways to simplify CLI usage is definetely needed.

I'm not entirely sure why `revanced-patches` and `revanced-integrations` aren't part of the CLI package. I'd say in most use cases they're both required to patch APKs so you might as well include them automatically.

I've created my own shell script to utilize ReVanced CLI. It's available in Gist in case anyone's interested - https://gist.github.com/gim-/75481a6fb43b7f8d09aa73fd02e5fe8a

**Comment by oSumAtrIX** [comment]
ReVanced CLI is agnostic to any app and patch

**Comment by gim-** [comment]
> ReVanced CLI is agnostic to any app and patch

Why though? Are there any patches apart from `revanced-patches` available which people might be using?

**Comment by oSumAtrIX** [comment]
Because it is by design featured to supply a combination of patch bundles and patch any app

**Comment by Ushie** [comment]
> > ReVanced CLI is agnostic to any app and patch
> 
> Why though? Are there any patches apart from `revanced-patches` available which people might be using?

Yes, ReVanced Patches aren't the only ones supported, I can make my own if I wanted to

The reason there aren't many non-official bundles is the lack of support in ReVanced Manager, but ReVanced Manager v2 will add support

**Comment by CoolnsX** [comment]
https://github.com/CoolnsX/revanced-build

**Comment by oSumAtrIX** [comment]
https://github.com/CoolnsX/revanced-build/blob/03c5e7d53fd6cfb0ebe85b15f458404e9af62ccb/revanced#L41

Refer to https://github.com/ReVanced/revanced-cli/issues/307#issuecomment-1860103114

**Comment by CoolnsX** [comment]
Bruh it can be made into anything, I m giving something to start from

**Comment by CoolnsX** [comment]
Will little curl and some logic, u can fetch the list of apps supported by revanced-cli

**Comment by oSumAtrIX** [comment]
Downloading apps is no business logic ReVanced CLI is involving. The scripts are supposed to simply run common commands form ReVanced CLI and not extend it with additional features.

**Comment by CoolnsX** [comment]
In that case, make an elaborate docs

**Comment by oSumAtrIX** [comment]
I am already assigned to the issue. I won't waste time on writing down what I know I need to do already

**Comment by CoolnsX** [comment]
and it's taking this much time, when it's only 2-3 hours work max

**Comment by oSumAtrIX** [comment]
That doesn't matter, I work on other more important things. If you want it quicker you'll have to familiarize yourself with the designs and concepts and implement it yourself.

**Comment by decipher3114** [comment]
> Downloading apps is no business logic ReVanced CLI is involving. The scripts are supposed to simply run common commands form ReVanced CLI and not extend it with additional features.

What are those common commands? Is there any specific usecase determined for it?

**Comment by oSumAtrIX** [comment]
It looks like the scripts don't add much value. Either they break design by supporting specific scenarios only, or they are too irrelevant, such as installing a JRE. The branch https://github.com/ReVanced/revanced-cli/tree/chore/scripts can be kept for reconsideration, however as of now this isn't planned anymore.
