### ISSUE TITLE
bug: cant patch with the CLI

### ISSUE THREAD

**Issue by analgaming12** [ReVanced/revanced-cli#322]
### Bug description

Step: 
download youtube v19.09.37 apk
patch with options: `java -jar revanced-cli-4.5.0-all.jar patch com.google.android.youtube_19.09.37-1544809920_minAPI26\(arm64-v8a\,armeabi-v7a\,x86\,x86_64\)\(nodpi\)_apkmirror.com.apk -o revanced.apk --patch-bundle=revanced-patches-4.4.0.jar -i=Remember video quality,Playback speed,Restore old video quality menu,Video ads,Hide ads,Disable resuming Shorts on startup,SponsorBlock,Change start page,Hide Shorts components,Hide breaking news shelf,Hide album cards,Hide layout components,Hide floating microphone button,Hide crowdfunding box,Hide seekbar,Return YouTube Dislike,Wide searchbar,Navigation buttons,Client spoof,Minimized playback,GmsCore support,Disable precise seeking gesture`(i included the quote marks but echo didnt like it)

### Additional context

The logs are attached:
[log.txt](https://github.com/ReVanced/revanced-cli/files/14794112/log.txt)
This seems to be similiar to an issue I had on my phone with patching, log is here:
[Errorlogpatching.txt - from phone](https://github.com/ReVanced/revanced-cli/files/14794147/Errorlogpatching.txt)

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by analgaming12** [comment]
This was with the newest everything, `revanced-cli-4.5.0-all.jar`, `revanced-patches.4.4.0.jar`, and the newest recommended youtube version `19.09.37`

**Comment by oSumAtrIX** [comment]
You are missing the integrations apk. You need to merge it with -m as explained in the patch error log.

**Comment by analgaming12** [comment]
damn you guys are helpful for cmV0YXJkcwo= like me. thanks a lot!
