### ISSUE TITLE
bug: Parameter -ii seems broken

### ISSUE THREAD

**Issue by adriaan1313** [ReVanced/revanced-cli#325]
### Bug description

Hello, I recently tried to patch a YouTube apk with the cli, but noticed that the `-ii` option seems broken.
First, I tried using the option like described in the docs:
`java -jar revanced-cli-4.5.0-all.jar patch -m=revanced-integrations-1.6.0.apk -b=revanced-patches-4.4.0.jar -ii 77 -ii 90 -ii 126 -ii 127 com.google.android.youtube_19.09.37.apk`
That gave `APK file 77 does not exist` and then the entire help page.
Then I replaced the spaces with =, as in the help page:
`java -jar revanced-cli-4.5.0-all.jar patch -m=revanced-integrations-1.6.0.apk -b=revanced-patches-4.4.0.jar -ii=77 -ii=90 -ii=126 -ii=127 com.google.android.youtube_19.09.37.apk`
This started patching, however, the packages with index 77, 90, 126 and 127 were still being excluded.
So I tried using `-i` with the names instead:
`java -jar revanced-cli-4.5.0-all.jar patch -m=revanced-integrations-1.6.0.apk -b=revanced-patches-4.4.0.jar -i "Custom branding" -i "GmsCore support" -i "Change package name" -i "Export all activities" com.google.android.youtube_19.09.37.apk`
This worked. This confirms that the problem is with the -ii option.
Patches:
- Custom branding
- GmsCore support
- Change package name
- Export all activities

(from revanced-patches-4.4.0.jar, with revanced-integrations-1.6.0.apk)

### Additional context

The revenced-cli version used in the examples is 4.5.0, but the same behaviour is seen with version 4.6.0.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
in your first command you mixed = with spaces. CLI parsing is handled by PicoCLI but I don't know if it handles what you tried properly. Apart from that the command looked fine and the error you got doesn't make sense

**Comment by Allypost** [comment]
The option isn't `-ii` but `--ii` (notice the extra dash)

**Comment by adriaan1313** [comment]
Yes, sorry. That works (both with spaces and equals signs). I still find it odd that it doesn't say `Unknown option: '-ii'`, like it does if you add `-someRandomString` to it.
(sorry for wasting your time)
