### ISSUE TITLE
Cannot uninstall ReVanced(root) easily by users

### ISSUE THREAD

**Issue by yuma2b** [revanced/revanced-cli#33]
Currently, Root Revanced YouTube cannot uninstall the script unless each file of "/ data / adb /" is completely deleted.
Even if you temporarily return to the original YouTube by reinstalling,  after restarting, it will automatically change to Revanced by the mount script.

The solution to this is,
First, the direct deletion of each Revanced file in "/ data / adb /" above,
Second, simplification of script uninstall by Magisk Module,
Third, stop grep of the mount script and write it with a fixed path to disable the mount script after uninstalling the application.

First, the most certain, but not something that everyone can do, you will be at a loss for the same question. Not even written in Revanced-Documents.
Your teram's revanced manager will support it in the future, maybe, but at least not now.

Second, if you're not using Magisk, you can't use the Magisk module, of course.
(Should I throw away the [Magisk module method](https://github.com/revanced/revanced-cli/pull/32) that is convenient for supporting other than Magisk, such as SuperSU? Currently YouTube is only compatible with Android 5.0 and above. That is, if it is a mobile that can start YouTube, it is compatible with Magisk. It shouldn't be a bad idea to consider if you really need to consider something other than Magisk, such as SuperSU.)

Third, [the amendment](https://github.com/yuma2b/revanced-cli/tree/For-Magisk). Get the application path directly from revanced-cli with the pm command, and describe it in the mount script.
https://github.com/yuma2b/revanced-cli/blob/450198056a68d31579c6c91ba94f8c574f5a3fff/src/main/kotlin/app/revanced/utils/adb/Adb.kt#L50-L54
https://github.com/yuma2b/revanced-cli/blob/450198056a68d31579c6c91ba94f8c574f5a3fff/src/main/kotlin/app/revanced/utils/adb/Constants.kt#L51-L61
Such a technique was also used in Vanced. As a result, if you reinstall the app, it will no longer be the path described in the mount script, so you can virtually assume that you have uninstalled Revanced.

If the Manager is delayed, write a manual removal method like "First" in Revanced-Documents, and improve it, for users.

**Comment by oSumAtrIX** [comment]
> Get the application path directly from revanced-cli with the pm command, and describe it in the mount script.
The mount will fail and you would be abusing that, this is not expected behavior when you reinstall the app. Magisk support can be added as an option but not as a replacement to the current system due to the mentioned problem of some people not having Magisk. For that reason, an uninstall option could be added to the CLI to unmount and delete the scripts it previously installed. The manager will be capable of this anyways.
