### ISSUE TITLE
feat(Youtube Music): Discord Rich Presence Integration

### ISSUE THREAD

**Issue by univers93** [ReVanced/revanced-cli#343]
### Feature description

Integration of Discord Rich Presence on YouTube Music would allow users to show the music they are currently listening to on Discord, similar to the existing integration with Spotify. This feature would display the song title, artist, album, and playback status, giving Discord friends insight into the user’s musical taste in real-time.

_Spotify's integration:_
![](https://github.com/pkg-dot-zip/YoutubeMusicDiscordRichPresenceCSharp/raw/master/docs/spotify_sonne.png?raw=true)

Exemple images taken from open source **desktop** projects:
**[YouTubeDiscordPresence by XFG16 for YouTube and YouTube msuic](https://github.com/XFG16/YouTubeDiscordPresence)**
![](https://github.com/XFG16/YouTubeDiscordPresence/blob/main/Screenshots/newUiExample.png?raw=true)

**[ytmusic_rpc by DjDeveloperr](https://github.com/DjDeveloperr/ytmusic_rpc)**
![Image](https://github.com/DjDeveloperr/ytmusic_rpc/blob/main/screenshots/1.png?raw=true)

### Motivation

**Why is this feature important?**
This feature would bridge the gap between two popular platforms, YouTube Music and Discord, enhancing user experience in several ways:

- Social Engagement: Users could easily share their music preferences and discoveries with friends on Discord, fostering conversations and connections. 
- Community Building: A shared music experience could create a stronger sense of community within the Revanced and Discord ecosystems. 
- Platform Integration: Integrating Discord Rich Presence would make Revanced more attractive to users who already use Discord, expanding its potential audience. 

**Use Case**
How would users benefit from this feature?
Users would be able to listen to music as they normally do. As they play different songs, their Discord profile would dynamically update to reflect their current listening activity. This would allow friends to see what they're listening to and potentially join them in the musical experience.

**Benefits**

- Enhanced Social Interaction: Facilitate music-related conversations and shared experiences with friends on Discord. 
- Increased Platform Appeal: Make Revanced more attractive to users who already use Discord, expanding its user base. 
- Improved User Experience: Provide a seamless integration between two popular platforms, enhancing overall user satisfaction. 
- Exclusivity and promotion: With Spotify, Revanced would be the only music platform to support Discord Rich Presence, wich would be an immense promotion for the project.

### Acknowledgements

- [x] This issue is not a duplicate of an existing feature request.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Using an external app satisfies the motivation

**Comment by univers93** [comment]
> Using an external app satisfies the motivation

Not possible on mobile, only desktop as stated.

**Comment by oSumAtrIX** [comment]
An external app can read notifications and use Discord API to display rich presence.

**Comment by bluesec-trinh** [comment]
> An external app can read notifications and use Discord API to display rich presence.

Would you happen to know of any apps that could do this?

**Comment by oSumAtrIX** [comment]
No, but tasker can read notifications and process them further, such as for a Discord RPC
