### ISSUE TITLE
bug: Improper text placement

### ISSUE THREAD

**Issue by decipher3114** [ReVanced/revanced-cli#345]
### Bug description

When printing patches, the `Enabled` key is printed on without a new line.
With descriptions, it is placed in the end of the `Description` key, and if descriptions are disabled, it is placed in the end of `Name` key
Here's how it looks:
1. Description enabled
```
Name: Hide seekbar
Description: Adds an option to hide the seekbar.Enabled: true
Compatible packages:
	Package name: com.google.android.youtube
```
2. Description disabled
```
Name: Hide seekbarEnabled: true
Compatible packages:
	Package name: com.google.android.youtube
```

### Solution

Fix this issue accordingly.

### Acknowledgements

- [x] This issue is not a duplicate of an existing bug report.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by decipher3114** [comment]
@oSumAtrIX 
```
INFO: Name: Export all activities
Enabled: false
```

The `INFO: ` is placed should not have anything adjacent to it and patches list must start from the new line.

**Comment by oSumAtrIX** [comment]
Thats how the logger is configured. We would need to arbitrarily prepend a newline to the output.

**Comment by decipher3114** [comment]
@oSumAtrIX  So, it won't be fixed?

**Comment by oSumAtrIX** [comment]
It is not a bug
