### ISSUE TITLE
feat: gui version for pc

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-cli#347]
### Feature description

The request is for a GUI version of revanced-cli which currently exists in a command-line (CLI) format on pc. This GUI version will allow users to interact with the program through visual components like buttons, menus, checkboxes, and other standard interface elements, rather than using text-based commands on pc. just like the android app

### Motivation

1
A GUI version of revanced-cli is essential because it transforms a text-based, command-line interface (CLI) into a visual, user-friendly experience. Many users find CLI interfaces difficult to learn and use, especially those who lack technical expertise or prefer interacting with a program in a more intuitive manner. By providing a GUI, the program will be more accessible to a broader audience, including non-technical users, without compromising the power and flexibility of the core functionality on pc. just like the android app
2
The explicit use case for the GUI version of revanced-cli is to allow users to efficiently patching apps without needing to memorize or type commands on pc. just like the android app
3
- Enhanced Usability: A GUI removes the need for users to memorize complex commands or syntax and typing it. This lowers the barrier to entry and enables users to focus on patching the app at hand instead of figuring out how to use the tool. just like the android app
- Increased Productivity: A visual interface provides a more efficient way to patch apps, just like the android app
- Broader Accessibility: Not all users are comfortable or familiar with the command line typing, particularly where non-technical users are involved on pc. A GUI makes the tool accessible to a wider audience, including those who may not be familiar with technical interfaces.just like the android app

4
The addition of a GUI version of revanced-cli is an essential step toward improving the user experience on pc, broadening accessibility just like the android app, and enhancing the effectiveness of the application. By making it easier for users to interact with the tool through a visual interface, this feature will foster greater adoption, higher productivity, and overall satisfaction. just like the android app

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Android is the first platform of ReVanced. ReVanced CLI is mainly used for development or programmatic applications. The motivations seem like generated by ChatGPT.  If you need a GUI, use ReVanced Manager.
