### ISSUE TITLE
feat: Allow the options to be parsed in any position

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-cli#349]
### Feature description

Options only work using the CLI, when passed right after the specific patch.
I.E. You'd have ' -e "Change header" -Oheader=premium*header'
and if you put anything Inbetween those two inputs like another patch for example, the patch no longer sees the options being passed.

Add the feature to add options in any position
I.e.
```
-e "Change header" -e "Custom branding" -e "Theme" -Oheader="premium*header" -OappName="YouTube" -OiconPath="icon" -OdarkThemeBackgroundColor="@android:color/system_neutral1_900" -OlightThemeBackgroundColor="@android:color/system_neutral1_50" 
```

### Motivation

It will make the use of options more easier

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Options are specific to patches. Two patches can have an option with the same key.
