### ISSUE TITLE
Turn off updates in Play Store using Magisk script

### ISSUE THREAD

**Issue by kakathic** [revanced/revanced-cli#37]
```bash
PK=com.google.android.youtube
PS=com.android.vending

LDB=/data/data/$PS/databases/library.db
LADB=/data/data/$PS/databases/localappstate.db 

cmd appops set --uid $PS GET_USAGE_STATS ignore pm disable $PS > /dev/null 2>&1 
./sqlite3 $LDB "UPDATE ownership SET doc_type = '25' WHERE doc_id = '$PK'"; 
./sqlite3 $LADB "UPDATE appstate SET auto_update = '2' WHERE package_name = '$PK'"; 

rm -rf /data/data/$PS/cache/* pm enable $PS > /dev/null 2>&1
```

Try the above code and you will be surprised when it will disappear the YouTube update button, I got these codes from the magisk module of: JumbomanXDA

Do this code every reboot, and just install the app it will no longer have the YouTube update button.

**Comment by oSumAtrIX** [comment]
We do not have a sqlite3 binary

**Comment by kakathic** [comment]
> Chúng tôi không có tệp nhị phân sqlite3



> We do not have a sqlite3 binary

I will look for the link

**Comment by kakathic** [comment]
> We do not have a sqlite3 binary

https://github.com/EXALAB/sqlite3-android/tree/master/binary

**Comment by AnyoeDove** [comment]
https://modules.lsposed.org/module/ru.mike.updatelocker

https://github.com/Dr-TSNG/Hide-My-Applist/

LSPosed(Xposed) modules are much easier solutions.

**Comment by oSumAtrIX** [comment]
This is out of scope for the CLI.
