### ISSUE TITLE
resources.zip failing to compile

### ISSUE THREAD

**Issue by WelsonLiong** [revanced/revanced-cli#39]
`brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMIN\AppData\Local\Temp\brut_util_Jar_121317490830691922272717766976781639223.tmp, compile, --dir, C:\Users\ADMIN\Documents\Revanced\revanced-cache\res, --legacy, -o, C:\Users\ADMIN\Documents\Revanced\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
        at app.revanced.patcher.Patcher.save(Patcher.kt:175)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:29)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:84)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMIN\AppData\Local\Temp\brut_util_Jar_121317490830691922272717766976781639223.tmp, compile, --dir, C:\Users\ADMIN\Documents\Revanced\revanced-cache\res, --legacy, -o, C:\Users\ADMIN\Documents\Revanced\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
        ... 13 more
Jun 19, 2022 1:27:37 PM brut.util.OS$StreamForwarder run
WARNING: C:\Users\ADMIN\Documents\Revanced\revanced-cache\build\resources.zip: error: The system cannot find the file specified. (2).`

**Comment by WelsonLiong** [comment]
![WindowsTerminal_RqQsZ0Iqzu](https://user-images.githubusercontent.com/89066255/174467549-660afb40-04d6-40e8-8e24-f298ec735be6.png)


> `brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMIN\AppData\Local\Temp\brut_util_Jar_121317490830691922272717766976781639223.tmp, compile, --dir, C:\Users\ADMIN\Documents\Revanced\revanced-cache\res, --legacy, -o, C:\Users\ADMIN\Documents\Revanced\revanced-cache\build\resources.zip] at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375) at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629) at app.revanced.patcher.Patcher.save(Patcher.kt:175) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:29) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:84) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ADMIN\AppData\Local\Temp\brut_util_Jar_121317490830691922272717766976781639223.tmp, compile, --dir, C:\Users\ADMIN\Documents\Revanced\revanced-cache\res, --legacy, -o, C:\Users\ADMIN\Documents\Revanced\revanced-cache\build\resources.zip] at brut.util.OS.exec(OS.java:99) at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371) ... 13 more Jun 19, 2022 1:27:37 PM brut.util.OS$StreamForwarder run WARNING: C:\Users\ADMIN\Documents\Revanced\revanced-cache\build\resources.zip: error: The system cannot find the file specified. (2).`

**Comment by LYB4** [comment]
use the 1.4.2 cli i think,

**Comment by Aunali321** [comment]
Delete apktook dir in appdata.
should be in C:\Users\Admin\AppData\Local\Apktool.
Fixed it for me.

**Comment by Sculas** [comment]
Commit 496f82121879443609667a792cc1e16441ef5c2f should've fixed this. Please let me know if you continue to get this error, and how I can reproduce it.

**Comment by dibyarupprk** [comment]
> Commit [496f821](https://github.com/revanced/revanced-cli/commit/496f82121879443609667a792cc1e16441ef5c2f) should've fixed this. Please let me know if you continue to get this error. And if so, how I can reproduce it.

yes it still gives the same error
method to reproduce: just just buiding with the required integrations on latest cli, patches and integration for the bumped yt version

**Comment by airend** [comment]
@Sculas, there must be a deeper issue, but if I get rid of the relativization on L28-29, it works fine (i.e., `filePath.deleteRecursively()`).

https://github.com/revanced/revanced-cli/blob/6b9751448caa61d96fbfa2f62d0a98f0e99e751a/src/main/kotlin/app/revanced/utils/filesystem/ZipFileSystemUtils.kt#L28-L29

**Comment by TheJeterLP** [comment]
> > Commit [496f821](https://github.com/revanced/revanced-cli/commit/496f82121879443609667a792cc1e16441ef5c2f) should've fixed this. Please let me know if you continue to get this error. And if so, how I can reproduce it.
> 
> I'm using the latest version of the patches, cli and integrations and I'm getting this collection is empty error
> 
> `[5,20] This method requires at least 1 registers, for the method parameters [5,20] This method requires at least 1 registers, for the method parameters [5,20] This method requires at least 1 registers, for the method parameters [5,20] This method requires at least 1 registers, for the method parameters [5,20] This method requires at least 1 registers, for the method parameters [5,20] This method requires at least 1 registers, for the method parameters [success] amoled [error] minimized-playback: app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty. at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264) at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282) at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.util.NoSuchElementException: Collection is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201) at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(InlineSmaliCompiler.kt:67) at app.revanced.patches.youtube.layout.minimizedplayback.patch.MinimizedPlaybackPatch.execute(MinimizedPlaybackPatch.kt:34) at app.revanced.patches.youtube.layout.minimizedplayback.patch.MinimizedPlaybackPatch.execute(MinimizedPlaybackPatch.kt:17) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262) ... 14 more [success] premium-heading [error] old-quality-layout: app.revanced.patcher.patch.implementation.misc.PatchResultError: old-quality-layout depends on integrations but the following error was raised: Collection is empty. at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:242) at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282) at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) [success] hide-cast-button [error] microg-support: app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty. at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264) at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282) at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.util.NoSuchElementException: Collection is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201) at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(InlineSmaliCompiler.kt:67) at app.revanced.patches.youtube.misc.microg.patch.bytecode.MicroGBytecodePatch.disablePlayServiceChecksAndFixCastIssues(MicroGBytecodePatch.kt:151) at app.revanced.patches.youtube.misc.microg.patch.bytecode.MicroGBytecodePatch.execute(MicroGBytecodePatch.kt:57) at app.revanced.patches.youtube.misc.microg.patch.bytecode.MicroGBytecodePatch.execute(MicroGBytecodePatch.kt:33) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262) ... 14 more [error] general-ads: app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty. at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264) at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282) at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.util.NoSuchElementException: Collection is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201) at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction(InlineSmaliCompiler.kt:77) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction$default(InlineSmaliCompiler.kt:77) at app.revanced.extensions.ExtensionsKt.injectHideCall(Extensions.kt:13) at app.revanced.patches.youtube.ad.general.bytecode.patch.GeneralBytecodeAdsPatch.execute(GeneralBytecodeAdsPatch.kt:106) at app.revanced.patches.youtube.ad.general.bytecode.patch.GeneralBytecodeAdsPatch.execute(GeneralBytecodeAdsPatch.kt:42) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262) ... 14 more [error] video-ads: app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty. at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264) at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282) at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.util.NoSuchElementException: Collection is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201) at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(InlineSmaliCompiler.kt:67) at app.revanced.patches.youtube.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:48) at app.revanced.patches.youtube.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:24) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262) ... 14 more [error] seekbar-tapping: app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty. at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264) at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282) at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.util.NoSuchElementException: Collection is empty. at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201) at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67) at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(InlineSmaliCompiler.kt:67) at app.revanced.patches.youtube.interaction.seekbar.patch.EnableSeekbarTappingPatch.execute(EnableSeekbarTappingPatch.kt:80) at app.revanced.patches.youtube.interaction.seekbar.patch.EnableSeekbarTappingPatch.execute(EnableSeekbarTappingPatch.kt:25) at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262) ... 14 more`

Same for me

**Comment by MedzikUser** [comment]
![](https://cdn.medzik.xyz/P7RS86t.png)

bruh
