### ISSUE TITLE
Issue when installing non-root version

### ISSUE THREAD

**Issue by XDream8** [revanced/revanced-cli#41]
![1655750528](https://user-images.githubusercontent.com/62709801/174662389-d498d3a0-2323-4593-87c6-6da308214718.png)

- the command used to create revanced.apk: ¨```java -jar revanced-cli.jar -a youtube.apk -c -o revanced.apk -b revanced-patches.jar -m integrations.apk -i general-resource-ads -i general-ads -i video-ads -i seekbar-tapping -i amoled -i premium-heading -i custom-branding -i hide-cast-button -i disable-create-button -i minimized-playback -i old-quality-layout -i microg-support```

**Comment by airend** [comment]
You need to `--install` it (otherwise, no signature).
