### ISSUE TITLE
error: signatures do not match previously installed version

### ISSUE THREAD

**Issue by naftali100** [revanced/revanced-cli#50]
```
se.vidstige.jadb.JadbException: Could not install revanced.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.google.android.youtube signatures do not match previously installed version; ignoring!]
```
i have the same yt version installed on my phone. 
uninstalling or downgrading it didn't help

**Comment by oSumAtrIX** [comment]
Wrong place.

**Comment by naftali100** [comment]
> It says the signature doesn't match, did you have YouTube already installed from the Playstore?

From apkmirror, i installed the same apk i patched

**Comment by DeeBeeDouble** [comment]
Any news on this? I'm having the exact same problem.
