### ISSUE TITLE
Chnge skipped text

### ISSUE THREAD

**Issue by Johannes7k75** [revanced/revanced-cli#58]
I would be really happy if the text on skipped would not just say `The package version is 17.24.34 and is incompatible.`.  
But would also say which version is supported for it such as Compatible is 17.23.34

Here the text i mean.
![grafik](https://user-images.githubusercontent.com/57235955/175141216-95a9640b-6346-487d-9014-883f5ccbce47.png)

**Comment by oSumAtrIX** [comment]
[Done](https://github.com/revanced/revanced-cli/commit/df85fa37ef067681a027e6fe9212c8a065d4981b).
