### ISSUE TITLE
Regarding support for rooted phones without Google components

### ISSUE THREAD

**Issue by Codename-Texas** [revanced/revanced-cli#70]
Hey, great project.

I'm running a Xiaomi phone with CrDroid ROM (Android 12, based on LineageOS) with Magisk for root access & the official MicroG project installed and configured instead of Google services,

Installing ReVanced somewhat works, though the `--mount` option is required, along with an existing unpatched YouTube app (downloaded from ApkMirror) for the installation to succeed, else nothing happens after the command on the desktop finishes.

I compiled without excluding MicroG support, and the app does work somewhat. It tends to crash on opening it often. My concern in this case is that the patched ReVanced app doesn't allow me to log into my Google account. I've tried using the old Vanced MicroG app which is opened through the `MicroG` option in RV's settings, and also logging in natively through my system's MicroG installation, though the accounts list remains empty no matter what.

So, I'd like to know whether this is intentional (lack of support for this kind of configuration) or some new bug. I imagine there's plenty of rooted phone users using this app, just not too many of those that don't have Google services.

**Comment by Canny1913** [comment]
Just install the root variant. (exclude microg-support) It should work

**Comment by Codename-Texas** [comment]
If I install it excluding `microg-support` then whenever I start RV I get the `YouTube won't run without Google Play services, which are not supported by your device.` message, which just closes the app once you press OK.

**Comment by polkaulfield** [comment]
> If I install it excluding `microg-support` then whenever I start RV I get the `YouTube won't run without Google Play services, which are not supported by your device.` message, which just closes the app once you press OK.

Same issue here, i had to end up using vanced microg... it doesnt hook to the normal microg

**Comment by Codename-Texas** [comment]
I recall this being an issue with legacy Vanced as well, as the root version never worked. However, in their case, using Vanced MicroG alongside it in non-root mode had mitigated the problem.

I suspect the culprit here is MicroG itself. During my time using it I noticed that not all of my apps would use it's messaging service (for use with push notifications). Notably, messaging platforms like Element and Signal would prompt that no GMS is found and that they will rely on websockets and similar for similar functionality. Why this happens - I'm not sure. But it would be great to get some developer input on this, as there is certainly a minority of people who refuse to use Google apps for well-defined reasons.

**Comment by Milor123** [comment]
I have the same issue, my phone is Poco x3 pro with CrDroid 12.1, rooted, magisk and microG installed from magisk package

The YouTube ReVanced **don't recognize my Google account devices added from my navite MicroG**, and when I try to add the account, it said that `already exits`. (And my Google account is correctly configured to **be visible to all apps in account settings**)

![image](https://user-images.githubusercontent.com/14153649/177013927-c6f3b6fb-4b45-4c4f-8ea9-7000c26719a2.png)

Only works when i keep the `microg-support` but then i must install the external app vanced MicroG, when i have installed the native MicroG

Any one solution guys/

**Comment by Milor123** [comment]
> Recuerdo que esto también fue un problema con el legado de Vanced, ya que la versión raíz nunca funcionó. Sin embargo, en su caso, el uso de Vanced MicroG junto con él en modo no root había mitigado el problema.
> 
> Sospecho que el culpable aquí es el propio MicroG. Durante el tiempo que lo usé, noté que no todas mis aplicaciones usarían su servicio de mensajería (para usar con notificaciones automáticas). En particular, las plataformas de mensajería como Element y Signal indicarán que no se encuentra ningún GMS y que se basarán en websockets y similares para una funcionalidad similar. ¿Por qué sucede esto? No estoy seguro. Pero sería genial obtener la opinión de los desarrolladores sobre esto, ya que ciertamente hay una minoría de personas que se niegan a usar las aplicaciones de Google por razones bien definidas.

In my case, i Can use Vanced an youtube (stock apk) and stay logged in my google apps using Native MicroG, it maybe was a old problem in vanced, but it is not problem now in vanced, and in ReVanced the problem returns!

**Comment by oSumAtrIX** [comment]
Not a CLI issue.
