### ISSUE TITLE
`INFO` log messages dont show during execution

### ISSUE THREAD

**Issue by bogadana** [revanced/revanced-cli#79]
info messages are only printed after the program exits, higher severity levels work as expected
seems to be caused by https://github.com/revanced/revanced-cli/commit/0ddc2b54b739dae3e8ccc983bab73fc84e72be0a

**Comment by oSumAtrIX** [comment]
Do you have any idea on why this happens?

**Comment by TheJeterLP** [comment]
Same for me. +1

**Comment by oSumAtrIX** [comment]
Can you review this @EdgE790

**Comment by bogadana** [comment]
not really familiar with java logger. seems like stdout isnt being flushed properly

**Comment by EdgE790** [comment]
Yep, exactly what happened. Will fix it

**Comment by bogadana** [comment]
default streamhandler doesnt flush on every message

ive managed to make this and it works but for some reason it prints the same thing twice
```kt
internal class FlushingStreamHandler(val out: OutputStream, val format: Formatter) : StreamHandler(out, format) {
    override fun publish(record: LogRecord) {
       super.publish(record)
       flush()
    }
}
```

**Comment by EdgE790** [comment]
@bogadana should I prepare PR or are you already working on it?

**Comment by bogadana** [comment]
i can leave it for you cause i have no idea whats wrong

**Comment by TheJeterLP** [comment]
@EdgE790 anything new?

**Comment by EdgE790** [comment]
@TheJeterLP Testing the fix, for now it seems ok.
