### ISSUE TITLE
youtube keeps crashing when trying to play videos on third party apps(eg. play store)

### ISSUE THREAD

**Issue by pWoLiAn** [revanced/revanced-cli#82]
youtube version: 17.24.34 (root variant)

I get the following toast and youtube crashes when trying to play app trailers

![image](https://user-images.githubusercontent.com/49567139/177253166-c53675f4-bc8d-4134-838d-074d9360d1ea.png)

Crash log : https://paste.crdroid.net/MBN1ir

This was a known bug in the latest vanced version too ( check [G] in https://t.me/c/1105197720/1478294 ), although the error in the crash log seems to be different one.

**Comment by TheJeterLP** [comment]
That tries to open Vanced. Not ReVanced. Uninstall Vanced and try again

**Comment by pWoLiAn** [comment]
> That tries to open Vanced. Not ReVanced. Uninstall Vanced and try again

Sorry that was the wrong log. this is the actual log : https://paste.crdroid.net/MBN1ir

**Comment by TheJeterLP** [comment]
> > That tries to open Vanced. Not ReVanced. Uninstall Vanced and try again
> 
> Sorry that was the wrong log. this is the actual log : https://paste.crdroid.net/MBN1ir

Yes that is from ReVanced. I Will take a look at it later and fix it.

**Comment by TheJeterLP** [comment]
Should be fixed with the newest integrations build. Please rebuild with that and then tell me if the error is gone.
https://github.com/revanced/revanced-integrations/releases/tag/v0.20.1

**Comment by TheJeterLP** [comment]
Works for me using latest integrations.
