### ISSUE TITLE
problem: listing patches requires input apk again

### ISSUE THREAD

**Issue by old4error** [revanced/revanced-cli#87]
# 🐞 Issue

i wanna look at the changes in patches file (to include/exclude new patches), but cli gives me an error Error: Missing required argument(s): --apk=<inputFile>

# ⚙ Reproduce
i use revanced aur package. command: revanced-cli (just alias to java -jar /usr/share/revanced/revanced-cli.jar) -b /usr/share/revanced/revanced-patches.jar -l

# 🛠 Solution
selecting vanilla youtube input apk is the solution

# ⚠ Additional context

**Comment by bogadana** [comment]
this is definitely a regression

**Comment by old4error** [comment]
but i could list patches without youtube.apk before

**Comment by bogadana** [comment]
introduced here https://github.com/revanced/revanced-cli/commit/131100ef0043924a9c11eb9886b4f6b0373690d9

**Comment by Itroublve** [comment]
I'll fix this once I get home.

**Comment by old4error** [comment]
@Itroublve also `--uninstall` argument need input apk. why program have to use file on pc to uninstall youtube on phone? i don't think it should work this way

**Comment by Itroublve** [comment]
> @Itroublve also `--uninstall` argument need input apk. why program have to use file on pc to uninstall youtube on phone? i don't think it should work this way

That is the intended way as there's no other user-friendly way to get package name

**Comment by shrihanDev** [comment]
Just to add my findings here that no one would care: The `-a` flag for the listing apparently will not care what you're passing, so something like `java -jar CLI.jar -a NeverGonnaGiveYouUp -b Patches.jar -l` still works...
