### ISSUE TITLE
feat: contributing guidelines

### ISSUE THREAD

**Issue by Aunali321** [ReVanced/revanced-cli#93]
**Is your feature request related to a problem? Please describe.**
Add a contributing.md in the repo so it's easier for new developers to know contributing guidelines.

**Describe the solution you'd like**
Add a contributing.md.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by oSumAtrIX** [comment]
RE: https://github.com/ReVanced/revanced-patches/blob/dev/CONTRIBUTING.md
